version: "3.7"

services:
  bitcoind:
    image: getumbrel/bitcoind:v28.0@sha256:95c5eb9778fc0050e185b22700061fb7e7d71a0c27860067461bed2afcfbe5c4
    volumes:
      - ${PWD}/bitcoin:/data/.bitcoin
    restart: on-failure
    stop_grace_period: 15m30s
    ports:
      - "18443:18443"
      # - "8333:8333" # "$BITCOIN_P2P_PORT:$BITCOIN_P2P_PORT"
  server:
    build: .
    depends_on: [bitcoind]
    command: ["npm", "start"]
    restart: on-failure
    ports:
      - "3005:3005"
    environment:
      PORT: "3005"
      BITCOIN_HOST: "bitcoind"
      RPC_PORT: $BITCOIN_RPC_PORT
      RPC_USER: $BITCOIN_RPC_USER
      RPC_PASSWORD: $BITCOIN_RPC_PASS
      BITCOIN_RPC_HIDDEN_SERVICE: "/var/lib/tor/bitcoin-rpc/hostname"
      BITCOIN_P2P_HIDDEN_SERVICE: "/var/lib/tor/bitcoin-p2p/hostname"

networks:
  default:
    name: umbrel_main_network
    ipam:
      driver: default
      config:
        - subnet: "$NETWORK_IP/24"
